from datetime import datetime

# Get biller name 
biller_name = input("Enter your name: ").strip()

# Collect items and quantities
items = []
while True:
    item = input("Enter item name (or press Enter to finish): ").strip()
    if not item:
        break
    try:
        quantity = int(input(f"Enter quantity for '{item}': "))
        price = float(input(f"Enter price per unit for '{item}': "))
        if quantity > 0 and price >= 0:
            items.append({"name": item, "qty": quantity, "price": price})
        else:
            print("Quantity and price must be positive. Try again.")
    except ValueError:
        print("Invalid input. Please enter numbers for quantity and price.")

# Build and print bill
now = datetime.now()
date_time_str = now.strftime("%B %d, %Y at %I:%M %p")

print("\n" + "=" * 50)
print("                    INVOICE BILL")
print("=" * 50)
print(f"Bill Generated by: {biller_name}")
print(f"Date & Time: {date_time_str}")
print("-" * 50)
print(f"{'Item':<20} {'Qty':>6} {'Price':>10} {'Amount':>10}")
print("-" * 50)

total = 0
for i in items:
    amount = i["qty"] * i["price"]
    total += amount
    print(f"{i['name']:<20} {i['qty']:>6} {i['price']:>10.2f} {amount:>10.2f}")

print("-" * 50)
print(f"{'TOTAL':<20} {'':>6} {'':>10} {total:>10.2f}")
print("=" * 50)
print(f"Thank you! Have a Great Day : {biller_name}")
print("=" * 50)