#include <iostream>
#include <iomanip>
#include <string>
#include <vector>
#include <ctime>

struct Item {
    std::string name;
    int quantity;
    double price;
};

int main() {
    std::string billerName;
    std::cout << "Enter your name: ";
    std::getline(std::cin, billerName);

    std::vector<Item> items;

    while (true) {
        std::string itemName;
        std::cout << "Enter item name (or press Enter to finish): ";
        std::getline(std::cin, itemName);

        if (itemName.empty()) break;

        Item item;
        item.name = itemName;

        std::cout << "Enter quantity for '" << itemName << "': ";
        std::cin >> item.quantity;
        std::cout << "Enter price per unit for '" << itemName << "': ";
        std::cin >> item.price;

        std::cin.ignore();

        if (item.quantity > 0 && item.price >= 0) {
            items.push_back(item);
        } else {
            std::cout << "Quantity and price must be positive. Try again.\n";
        }
    }

    // Get current date and time
    std::time_t now = std::time(nullptr);
    std::tm* localTime = std::localtime(&now);
    char dateTimeBuf[80];
    std::strftime(dateTimeBuf, sizeof(dateTimeBuf), "%B %d, %Y at %I:%M %p", localTime);

    // Print bill
    std::cout << "\n" << std::string(50, '=') << "\n";
    std::cout << "                    Invoice BILL\n";
    std::cout << std::string(50, '=') << "\n";
    std::cout << "Bill Generated by: " << billerName << "\n";
    std::cout << "Date & Time: " << dateTimeBuf << "\n";
    std::cout << std::string(50, '-') << "\n";
    std::cout << std::left << std::setw(20) << "Item" 
              << std::right << std::setw(6) << "Qty" 
              << std::setw(10) << "Price" 
              << std::setw(10) << "Amount" << "\n";
    std::cout << std::string(50, '-') << "\n";

    double total = 0;
    for (const auto& i : items) {
        double amount = i.quantity * i.price;
        total += amount;
        std::cout << std::left << std::setw(20) << i.name 
                  << std::right << std::setw(6) << i.quantity 
                  << std::setw(10) << std::fixed << std::setprecision(2) << i.price 
                  << std::setw(10) << amount << "\n";
    }

    std::cout << std::string(50, '-') << "\n";
    std::cout << std::left << std::setw(20) << "TOTAL" 
              << std::right << std::setw(6) << "" << std::setw(10) << "" 
              << std::setw(10) << std::fixed << total << "\n";
    std::cout << std::string(50, '=') << "\n";
    std::cout << "Thank you! Bill prepared by: " << billerName << "\n";
    std::cout << std::string(50, '=') << "\n";

    return 0;
}